version: "3.7"

services:
    nextjs:
        build:
            context: .
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        networks:
            - samm-network
        ports:
            - "3000:3000"
    keycloak:
        image: quay.io/keycloak/keycloak:19.0.1
        command: start-dev
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
            - 8080:8080

networks:
    samm-network:
        driver: bridge